services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USERNAME: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - rag_demo_data:/var/lib/postgresql/data

volumes:
  rag_demo_data:
